apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-app-deployment-ms-pedido
spec:
  replicas: 2
  selector:
    matchLabels:
      app: express-app-ms-pedido
  template:
    metadata:
      labels:
        app: express-app-ms-pedido
    spec:
      containers:
        - name: express-container-ms-pedido
          image: acrlanchonete.azurecr.io/lanchonetecreusa-ms-pedido:{{.Values.imageTag}}
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: lanchonete-configmap
                  key: MONGO_URI_PEDIDO
            - name: QUEUE_HOST
              valueFrom:
                configMapKeyRef:
                  name: lanchonete-configmap
                  key: QUEUE_HOST
            - name: QUEUE_PEDIDOS_NAME
              valueFrom:
                configMapKeyRef:
                  name: lanchonete-configmap
                  key: QUEUE_PEDIDOS_NAME
            - name: QUEUE_PAGAMENTOS_NAME
              valueFrom:
                configMapKeyRef:
                  name: lanchonete-configmap
                  key: QUEUE_PAGAMENTOS_NAME
            - name: QUEUE_PRODUCAO_NAME
              valueFrom:
                configMapKeyRef:
                  name: lanchonete-configmap
                  key: QUEUE_PRODUCAO_NAME
            - name: QUEUE_PRONTOS_NAME
              valueFrom:
                configMapKeyRef:
                  name: lanchonete-configmap
                  key: QUEUE_PRONTOS_NAME
