apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-app-deployment-ms-producao
spec:
  replicas: 2
  selector:
    matchLabels:
      app: express-app-ms-producao
  template:
    metadata:
      labels:
        app: express-app-ms-producao
    spec:
      containers:
        - name: express-container-ms-producao
          image: acrlanchonete.azurecr.io/lanchonetecreusa-ms-producao:{{.Values.imageTag}}
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: lanchonete-configmap
                  key: MONGO_URI_PRODUCAO
            - name: QUEUE_HOST
            - name: QUEUE_PRODUCAO_NAME
              valueFrom:
                configMapKeyRef:
                  name: lanchonete-configmap
                  key: QUEUE_PRODUCAO_NAME
            - name: QUEUE_PRONTOS_NAME
              valueFrom:
                configMapKeyRef:
                  name: lanchonete-configmap
                  key: QUEUE_PRONTOS_NAME
              valueFrom:
                configMapKeyRef:
                  name: lanchonete-configmap
                  key: QUEUE_HOST