apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: express-app-hpa-ms-producao
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: express-app-deployment-ms-producao
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80