apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-app-deployment-ms-pagamento
spec:
  replicas: 2
  selector:
    matchLabels:
      app: express-app-ms-pagamento
  template:
    metadata:
      labels:
        app: express-app-ms-pagamento
    spec:
      containers:
        - name: express-container-ms-pagamento
          image: acrlanchonete.azurecr.io/lanchonetecreusa-ms-pagamento:{{.Values.imageTag}}
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: lanchonete-configmap
                  key: MONGO_URI_PAGAMENTO
            - name: MS_PEDIDO_URL
              valueFrom:
                configMapKeyRef:
                  name: lanchonete-configmap
                  key: MS_PEDIDO_URL