apiVersion: v1
kind: Service
metadata:
  name: express-app-loadbalancer-service-ms-pagamento
spec:
  selector:
    app: express-app-ms-pagamento
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer