name: Deploy to AKS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Azure CLI
      uses: azure/setup-azure-cli@v1
      with:
        azcliversion: latest
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Configure kubectl
      uses: azure/k8s-set-context@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        cluster-name: kubernetes_cluster
        resource-group: resource_lanchonete

    - name: Apply Kubernetes Manifests
      run: |
        kubectl apply -f k8s/rabbitmq --force